In [1]:
import numpy as np

In [8]:
a=np.arange(2*2*2).reshape(2,2,2)
print(a)
np.dsplit(a,2)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [12]:
a=np.random.randint(1,10,size=20)
a

array([3, 2, 8, 5, 4, 1, 2, 4, 9, 7, 2, 9, 3, 4, 1, 3, 9, 5, 2, 4])

In [15]:
np.unique(a)
#//tell u how many unique use come in our website

array([1, 2, 3, 4, 5, 7, 8, 9])

In [27]:
a=np.random.randint(1,10,size=20)
b=np.random.randint(1,10,size=5)
print(a,b, sep='/n')
np.in1d(b,a)

[1 1 5 9 3 4 4 4 6 5 8 8 6 8 3 7 2 6 8 1]/n[7 4 6 3 8]


array([ True,  True,  True,  True,  True])

In [28]:
[True if x in a else False for x in b]
np.in1d(b,a)
#if u find a particular person available in list

array([ True,  True,  True,  True,  True])

In [30]:
np.intersect1d(b,a)
#those vaues which are same in both a and b

array([3, 4, 6, 7, 8])

In [33]:
np.union1d(b,a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
['yes' if x in a else 'no' for x in b]

['yes', 'yes', 'yes', 'yes', 'yes']

In [37]:
a=np.random.randint(1,10,size=20)
b=np.random.randint(1,10,size=5)
print(a,b, sep='/n')
np.setdiff1d(b,a)

#show which function are notin data base

[9 6 8 6 8 3 9 4 2 2 7 6 8 5 3 7 3 7 4 9]/n[8 7 9 4 1]


array([1])

In [38]:
a=np.random.randint(1,10,size=20)
b=np.random.randint(1,10,size=5)
print(a,b, sep='/n')
np.setxor1d(b,a)

[7 8 5 6 8 4 1 9 2 5 9 1 4 4 6 9 9 8 3 7]/n[4 8 7 9 8]


array([1, 2, 3, 5, 6])

In [40]:
np.save('abc.npy',a)