In [2]:
import numpy as np

In [2]:
l1=np.random.randn(2,2)
print(l1)
print(l1.ndim)
print(l1.shape)

[[ 1.47840076 -0.94114684]
 [-0.12620991 -0.97186048]]
2
(2, 2)


In [3]:
l2=np.arange(27).reshape((3,3,3))
print(l2)
l2[1,1,2]
l2.itemsize

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


4

In [7]:
%time l2=l2+6

Wall time: 0 ns


In [8]:
 l2[l2 % 2==0]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

# np.array make deep copy means new physical address
np.asarray make shalow copy physical adress is same


In [9]:
a=np.zeros((3,3))
#\np.ones(3,3)
a

#np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.full((3,3,3),5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [11]:
np.full_like(a,10)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [12]:
np.empty((3,3,3))

array([[[1.26276817e-311, 1.26273304e-311, 0.00000000e+000],
        [0.00000000e+000, 7.56587583e-307, 1.16096346e-028],
        [1.04857803e-142, 1.16467185e-028, 6.03677865e-154]],

       [[1.81152935e-152, 1.50102772e-153, 8.94279358e+130],
        [2.36947940e-038, 9.11160143e+130, 4.58111229e-072],
        [6.14099441e-071, 9.61822922e+140, 1.58063099e-153]],

       [[8.53719280e+136, 5.10072249e-038, 8.48606448e+136],
        [3.00300568e-067, 1.81152936e-152, 1.58085528e-153],
        [7.78045999e-143, 8.03408123e-095, 1.05894728e-153]]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye??

## data type can change in nd array

In [15]:
a=np.arange(1,13,dtype= 'float')
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [18]:
a=np.arange(1,13,dtype='g').reshape((4,3))

In [19]:
print(a.dtype)

float64


In [20]:
print(a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [22]:
np.full_like(a,5,dtype=a.dtype)
#a.dtype mean same data type

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]], dtype=float64)

In [25]:
a[a%3==0]
a%3==0

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [26]:
a[a%3==0]

array([ 3.,  6.,  9., 12.], dtype=float64)

In [29]:
a[(a%3==0) & (a%6==0)]

array([ 6., 12.], dtype=float64)